apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u5gpe75ef-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:bf3324ff917c54433c443634a91290fe8bfc7bd5@sha256:1074ebc295710c2e3d151e84fa1a3f7c4aa77f2312e5a8059ee967f99bc6242b
          name: container-image
